-- Fix user passwords with correct BCrypt hash for "password123"
USE ero_db;

-- Delete old users
DELETE FROM users WHERE username IN ('ambulance1', 'ambulance2', 'officer1', 'officer2', 'hospital1', 'control', 'guest');

-- Insert users with correct password hash (generated by Spring's BCryptPasswordEncoder)
-- You can generate these by registering through the API
INSERT INTO users (id, username, password, role, full_name, phone, email, is_active, created_at)
VALUES
('user-traffic-001', 'officer1', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'TRAFFIC', 'Rajesh Kumar', '+91-9876543210', 'rajesh@traffic.gov.in', true, NOW()),
('user-traffic-002', 'officer2', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'TRAFFIC', 'Priya Sharma', '+91-9876543211', 'priya@traffic.gov.in', true, NOW()),
('user-ambulance-001', 'ambulance1', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'AMBULANCE', 'Suresh Patil', '+91-9876543212', 'suresh@ems.com', true, NOW()),
('user-ambulance-002', 'ambulance2', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'AMBULANCE', 'Anita Reddy', '+91-9876543213', 'anita@ems.com', true, NOW()),
('user-hospital-001', 'hospital1', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'HOSPITAL', 'Dr. Ramesh', '+91-9876543214', 'ramesh@hospital.com', true, NOW()),
('user-control-001', 'control', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'CONTROL', 'Control Room Admin', '+91-9876543215', 'admin@ero.gov.in', true, NOW()),
('user-citizen-001', 'guest', '$2a$10$/rpORbek7gEeyRj0ptpYbeDKayjnEdzoKl3ndQ/308qE81xP1OEYS', 'CITIZEN', 'Guest User', '', '', true, NOW());

-- Update hospital admin reference
UPDATE hospitals SET admin_user_id = 'user-hospital-001' WHERE id = 'hosp-001';

SELECT 'Passwords fixed! All accounts now use: password123' as Status;
SELECT username, role, full_name FROM users ORDER BY role, username;
